### ISSUE TITLE
Links no funcionan en Github pages

### ISSUE THREAD

**Issue by PierBover** [es-vuejs/vuejs.org#2]
Las URLs que se generan en los links de los docs son con el formato:

https://es-vuejs.github.io/v2/guide/instance.html

Pero para que funcionen se debe poner el repo `vuejs.org`:

https://es-vuejs.github.io/vuejs.org/v2/guide/instance.html

No estoy familiarizado con Github pages.

Hay forma de arreglar esto?

**Comment by zeratulmdq** [comment]
El problema es la forma en la que esta armada la estructura de Hexo. Abrí un [issue](https://github.com/vuejs/vuejs.org/issues/761) indicando el problema en el repo original, y arreglé algunas cosas para este fork (no se cargaba ningún enlace ni recurso JS, CSS o imágenes correctamente) pero veo que me faltaron los enlaces en la barra lateral. En la build de hoy a la noche lo soluciono.

**Comment by zeratulmdq** [comment]
Subí la traducción parcial de la API y acomodé los links, creo que está todo bien, probalo y vemos cualquier cosa.
